parameters:
  - name: resourceGroupName
    type: string
    # default: 'myResourceGroup'

  - name: ipAddress
    type: string
    # default: 'myIp'

  - name: vmName
    type: string
    # default: 'myVM'

trigger:
  - none  # Specify the branch to trigger the pipeline

pool:
   name: 'myselfhostedagent'

variables:
  resourceGroupName: ${{ parameters.resourceGroupName }}
  ipAddress: ${{ parameters.ipAddress }}
  vmName: ${{ parameters.vmName }}

steps:

- script: |
    echo "Resource Group Name: $resourceGroupName"
    echo "IP Address: $ipAddress"
    echo "VM Name: $vmName"
  displayName: 'Debug Variables'

# - script: 'terraform init'
#   displayName: 'Terraform Init'

# - script: 'terraform validate'
#   displayName: 'Terraform Validate'

# - script: 'terraform plan -var="resourceGroupName"=$(resource_group_name) -var="ipAddress"=$(public_ip_name) -var="vmName"=$(virtual_machine_name) -var-file="myproject.dev.tfvars" '
#   displayName: 'Terraform Plan'

# - script: 'terraform apply  -var="resourceGroupName"=$(resource_group_name) -var="ipAddress"=$(public_ip_name) -var="vmName"=$(virtual_machine_name) -var-file="myproject.dev.tfvars" '
#   displayName: 'Terraform Apply'

# - script: 'terraform destroy -var-file="myproject.dev.tfvars" -auto-approve'
#   displayName: 'Terraform destroy'