parameters:
- name: resource_group_name
  displayName: Resource Group Name
  type: string

- name: public_ip_name
  displayName: Public IP Address Name
  type: string

- name: virtual_machine_name
  displayName: Virtual Machine Name
  type: string

trigger:
  - none  # Specify the branch to trigger the pipeline

pool:
   name: 'myselfhostedagent'

steps:

- script: 'terraform init'
  displayName: 'Terraform Init'

- script: 'terraform validate'
  displayName: 'Terraform Validate'

- script: 'terraform plan -var="resource_group_name"=$(resource_group_name) -var="public_ip_name"=$(public_ip_name) -var="virtual_machine_name"=$(virtual_machine_name) -var-file="myproject.dev.tfvars" '
  displayName: 'Terraform Plan'

- script: 'terraform apply -var="resource_group_name"=$(resource_group_name) -var="public_ip_name"=$(public_ip_name) -var="virtual_machine_name"=$(virtual_machine_name) -var-file="myproject.dev.tfvars" -auto-approve'
  displayName: 'Terraform Apply'

# - script: 'terraform destroy -var-file="myproject.dev.tfvars" -auto-approve'
#   displayName: 'Terraform destroy'