trigger:
  - none  # Specify the branch to trigger the pipeline

pool:
   name: 'myselfhostedagent'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.1.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: 'terraform init'
  displayName: 'Terraform Init'

- script: 'terraform validate'
  displayName: 'Terraform Validate'

- script: 'terraform plan -var-file="myproject.dev.tfvars" '
  displayName: 'Terraform Plan'

- script: 'terraform apply -var-file="myproject.dev.tfvars" -auto-approve'
  displayName: 'Terraform Apply'
