parameters:
- name: resourceGroup
  displayName: Resource Group Name
  type: string

- name: pub_ip_address
  displayName: Public IP Address Name
  type: string

- name: vm_name
  displayName: Virtual Machine Name
  type: string

trigger:
  - none  # Specify the branch to trigger the pipeline

pool:
   name: 'myselfhostedagent'

steps:

- script: 'terraform init'
  displayName: 'Terraform Init'

- script: 'terraform validate'
  displayName: 'Terraform Validate'

- script: 'terraform plan -var="resourceGroup"=$(resource_group_name) -var="pub_ip_address"=$(public_ip_name) -var="vm_name"=$(virtual_machine_name) -var-file="myproject.dev.tfvars" '
  displayName: 'Terraform Plan'

- script: 'terraform apply -var="resourceGroup"=$(resource_group_name) -var="pub_ip_address"=$(public_ip_name) -var="vm_name"=$(virtual_machine_name) -var-file="myproject.dev.tfvars" -auto-approve'
  displayName: 'Terraform Apply'

# - script: 'terraform destroy -var-file="myproject.dev.tfvars" -auto-approve'
#   displayName: 'Terraform destroy'